from __future__ import annotations

from enum import StrEnum


class Mode(StrEnum):
    ONBOARDING = "ONBOARDING"
    STORY = "STORY"
    CHOICE = "CHOICE"
    EXPLAIN = "EXPLAIN"
    INTERMISSION = "INTERMISSION"
    COMPLETE = "COMPLETE"
    NAV = "NAV"


class InterruptKind(StrEnum):
    WHY = "WHY"
    PAUSE = "PAUSE"
    REWIND = "REWIND"
    COMPARE = "COMPARE"
    CHANGE_TONE = "CHANGE_TONE"


class UIActionType(StrEnum):
    SET_SCENE = "SET_SCENE"
    SHOW_ACT_REVEAL = "SHOW_ACT_REVEAL"
    SHOW_INTERMISSION = "SHOW_INTERMISSION"
    SHOW_STORYBOARD = "SHOW_STORYBOARD"
    PLAY_VIDEO = "PLAY_VIDEO"
    SHOW_INTERLEAVED_BLOCKS = "SHOW_INTERLEAVED_BLOCKS"
    SHOW_CHOICES = "SHOW_CHOICES"
    UPDATE_TIMELINE = "UPDATE_TIMELINE"
    SHOW_REALITY_ANCHOR = "SHOW_REALITY_ANCHOR"
    SHOW_EXPLAIN_OVERLAY = "SHOW_EXPLAIN_OVERLAY"
    SET_MODE = "SET_MODE"
    CAPTION_APPEND = "CAPTION_APPEND"


class DirectorSignalType(StrEnum):
    STORY_BRIEF_CAPTURED = "STORY_BRIEF_CAPTURED"
    CONTINUE_ACT = "CONTINUE_ACT"
    INTERRUPT = "INTERRUPT"
    READY_FOR_CHOICES = "READY_FOR_CHOICES"
    PACE_HINT = "PACE_HINT"
    EMOTION_TARGET = "EMOTION_TARGET"


class AssetType(StrEnum):
    STORYBOARD = "storyboard"
    HERO_VIDEO = "hero_video"


class AssetStatus(StrEnum):
    PENDING = "pending"
    READY = "ready"
    FAILED = "failed"


class EventType(StrEnum):
    SESSION_STARTED = "SESSION_STARTED"
    BEAT_STARTED = "BEAT_STARTED"
    BEAT_ENDED = "BEAT_ENDED"
    INTERLEAVED_GENERATION_STARTED = "INTERLEAVED_GENERATION_STARTED"
    INTERLEAVED_READY = "INTERLEAVED_READY"
    INTERLEAVED_FAILED = "INTERLEAVED_FAILED"
    CHOICES_SHOWN = "CHOICES_SHOWN"
    CHOICE_SELECTED = "CHOICE_SELECTED"
    USER_INTERRUPT = "USER_INTERRUPT"
    SHOTPLAN_CREATED = "SHOTPLAN_CREATED"
    STORYBOARD_JOB_STARTED = "STORYBOARD_JOB_STARTED"
    STORYBOARD_READY = "STORYBOARD_READY"
    VIDEO_JOB_STARTED = "VIDEO_JOB_STARTED"
    VIDEO_READY = "VIDEO_READY"
    UI_ACTION_EMITTED = "UI_ACTION_EMITTED"
    UI_ACTION_ACKED = "UI_ACTION_ACKED"
    GRAPH_EDGE_ADDED = "GRAPH_EDGE_ADDED"
    EXPLAIN_ANSWERED = "EXPLAIN_ANSWERED"
    COMPARE_ANSWERED = "COMPARE_ANSWERED"
    SAFETY_REWRITE = "SAFETY_REWRITE"


class InterleavedTrigger(StrEnum):
    BEAT_START = "BEAT_START"
    COMPARE = "COMPARE"
